# Generated by Django 2.2 on 2021-01-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210123_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='type',
            field=models.CharField(choices=[('password_reset', 'Восстановление пароля'), ('register', 'Регистрация')], default='register', max_length=20, verbose_name='Тип токена'),
        ),
    ]
